### ISSUE TITLE
tool not working with new HMC xsd schema

### ISSUE THREAD

**Issue by adejoux** [PowerHMC/HmcRestClient#2]
Hello,

this client is really great to learn how the api is working. Thanks for it. :)

I have a problem with hmc 8.5.0 when fetching PCM informations: 

```````
        Performance and Capacity Monitoring        
=============================================================
1. ManagedSystemPcmPreference
2. LongTermMonitor
3. ShortTermMonitor
4. ProcessorMetrics
5. Return to MainMenu
6. Help
7. Exit

Enter your Choice: 2
sh: cls: command not found

Available ManagedSystems : 
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/py3/bin/HmcRestClient", line 9, in <module>
    load_entry_point('HmcRestClient==1.0', 'console_scripts', 'HmcRestClient')()
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/main/Main.py", line 134, in main
    menu()
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/main/Main.py", line 110, in menu
    performance_capacity_monitoring(choice, client.ip, client.x_api_session)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/main/PerformanceCapacityMonitor.py", line 43, in performance_capacity_monitoring
    get_managedsystem_uuid(ip, x_api_session)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/common/SelectManagedSystem.py", line 29, in get_managedsystem_uuid
    object_list = managedsystem_object.list_ManagedSystem(ip, x_api_session)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/managed_system/ListManagedSystem.py", line 50, in list_ManagedSystem
    self.content_type, "ManagedSystem", session_id)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/common/ListModule.py", line 65, in listing
    xml_object = UOM.CreateFromDocument(xmlstring)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/generated_src/UOM.py", line 65, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/local/var/pyenv/versions/3.4.5/lib/python3.4/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/var/pyenv/versions/3.4.5/lib/python3.4/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/var/pyenv/versions/3.4.5/lib/python3.4/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/private/var/folders/6t/jzq4fbq154nbkbhzdd2f6njc0000gn/T/python-build.20161117090425.38397/Python-3.4.5/Modules/pyexpat.c", line 405, in StartElement
  File "/usr/local/var/pyenv/versions/3.4.5/lib/python3.4/xml/sax/expatreader.py", line 354, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/saxer.py", line 370, in startElementNS
    binding_object = this_state.startBindingElement(type_class, new_object_factory, element_decl, attrs)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/saxer.py", line 207, in startBindingElement
    self.__constructElement(new_object_factory, attrs)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/saxer.py", line 135, in __constructElement
    self.__bindingInstance._setAttribute(attr_en, attrs.getValue(attr_name))
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/basis.py", line 2240, in _setAttribute
    au.set(self, value_lex, from_xml=True)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/content.py", line 278, in set
    new_value = self.__dataType.Factory(new_value, _from_xml=from_xml)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/basis.py", line 305, in Factory
    rv = cls._DynamicCreate(*args, **kw)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/basis.py", line 677, in _DynamicCreate
    return ctor(*args, **kw)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/basis.py", line 929, in __init__
    self.xsdConstraintsOK(location)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/basis.py", line 1055, in xsdConstraintsOK
    return self.XsdConstraintsOK(self, location)
  File "/usr/local/var/pyenv/versions/py3/lib/python3.4/site-packages/pyxb/binding/basis.py", line 1050, in XsdConstraintsOK
    raise pyxb.SimpleFacetValueError(cls, value, f, location)
pyxb.exceptions_.SimpleFacetValueError: Type {http://www.ibm.com/xmlns/systems/power/firmware/uom/mc/2012_10/}SchemaVersion.Enum enumeration constraint violated by value V1_4_0

``````

**Comment by Niraj-Shah-1** [comment]
HmcRestClient used PyXB XML parser to transform XML into Python objects and viceversa. UOM.py is a generated source code by PyXB libraries. In this case ListModule is using UOM.py to parse ManagedSystem list XML and load data into Python object and it is getting parsing error due to SchemaVersion.Enum enumeration constraint is violated. The HMC 8.5.0 is using new schema, it is sending response for schema version V1_4_0. The HmcRestClient was written against HMC 8.2.0 version i.e. schema version V1_2_0 hence you are seeing parsing error. Couple of options to resolve the error,
1. Uplift the generated_src for HMC 8.5.0 schema by doing PyXB compilation. (It is little tricky though!)
2. HMC sends response in latest schema version if it is not specified. If client wants response in older schema format client should explicitely specify SchemaVersion. You can modify ListModule.listing to explicitely send SchemaVersion as V1_2_0 in the request. HMC should respond back for the SchemaVersion V1_2_0.

**Comment by adejoux** [comment]
Ok. I saw your explanation about umdating the generated_src in your readme but I was not thinking it was the issue here.My bad :)

Thanks

**Comment by kumarBiplab1987** [comment]
@Niraj-Shah-1 Reference to your second option, can you let me know with an example how to send a request mentioning SchemaVersion

**Comment by Niraj-Shah-1** [comment]
@kumarBiplab1987 Please refer to the [HMC REST APIs](https://www.ibm.com/support/knowledgecenter/TI0003N/p8ehl/apis/RequestHeaders.htm) documentation. You can specify SchemaVersion using `X-HMC-Schema-Version` HTTP Header.
