### ISSUE TITLE
After Installtion Problem

### ISSUE THREAD

**Issue by ghost** [PowerHMC/HmcRestClient#3]
After installation become this error message:

```
#> HmcRestClient
Traceback (most recent call last):
  File "/bin/HmcRestClient", line 9, in <module>
    load_entry_point('HmcRestClient==1.0', 'console_scripts', 'HmcRestClient')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/HmcRestClient-1.0-py2.7.egg/src/main/Main.py", line 18, in <module>
    from src.main.HmcRestClient import *
  File "/usr/lib/python2.7/site-packages/HmcRestClient-1.0-py2.7.egg/src/main/HmcRestClient.py", line 21, in <module>
    from src.generated_src import UOM
  File "/usr/lib/python2.7/site-packages/HmcRestClient-1.0-py2.7.egg/src/generated_src/UOM.py", line 24, in <module>
    raise pyxb.PyXBVersionError(_PyXBVersion)
pyxb.exceptions_.PyXBVersionError: 1.2.4
```

Can you help me?

**Comment by kairoaraujo** [comment]
Install using the correct pyxb version.

```
# pip install pyxb==1.2.4
Collecting pyxb==1.2.4
  Downloading PyXB-1.2.4.tar.gz (8.7MB)
    100% |████████████████████████████████| 8.7MB 123kB/s
Installing collected packages: pyxb
  Running setup.py install for pyxb ... done
Successfully installed pyxb-1.2.4
```
