### ISSUE TITLE
ImportError: No module named 'msvcrt'

### ISSUE THREAD

**Issue by arpadhajdu** [PowerHMC/HmcRestClient#4]
Hi,

I tried to experiment with the proejct ... but I have the following issue running on Linux - Centos 7:

Python 3.4.5

Modules:
certifi (2018.1.18)
chardet (3.0.4)
feedparser (5.2.1)
HmcRestClient (1.0)
idna (2.6)
pip (9.0.1)
PyXB (1.2.4)
requests (2.18.4)
setuptools (19.2)
urllib3 (1.22)

[root@centosdeploy HmcRestClient]# HmcRestClient
Traceback (most recent call last):
  File "/usr/bin/HmcRestClient", line 9, in <module>
    load_entry_point('HmcRestClient==1.0', 'console_scripts', 'HmcRestClient')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/main/Main.py", line 18, in <module>
    from src.main.HmcRestClient import *
  File "/usr/lib/python3.4/site-packages/HmcRestClient-1.0-py3.4.egg/src/main/HmcRestClient.py", line 27, in <module>
    import msvcrt
ImportError: No module named 'msvcrt'

There were not any statement that the tool is Windows only ... but assuming the msvcrt dependency it seems it is ... 

Any plans to make it Linux compatible ?

**Comment by arpadhajdu** [comment]
Solved. Getch ... sorry I did not see it in readme..
